### PR TITLE
Typewriter: Handle tags more robustly

### PR DESCRIPTION
**Pull request by bucket3432**
See the individual commit messages for more details.

Summary:

- Refactor the partitioning logic in `typewrite_line` to use a state machine-based approach
- For an `active_char` immediately following an override block, ensure that the override block is put in `start`
  - It was previously being deleted accidentally.
- Treat text tags `\N`, `\n` and `\h` as single characters and remove the hackfix
  - With this change, it should now be trivial to support the libass extension `\{` if so desired.

### CODE REVIEW

**Comment by bucket3432** [comment]
Ugh, don't review this yet. I just tested it in my real-world example and it's not working as expected.

**Comment by bucket3432** [comment]
Okay, I've pushed an update and everything should be working as expected. The issue was that it was not recognizing multiple override blocks at the start because the lookahead in L189 was starting at the wrong position. `start_tags` is now being prepended to `start` after `active_char` is assigned so that `start` is a prefix of `text` during the loop.

**Comment by bucket3432** [comment]
Pushed another update that fixed a timing mismatch introduced with the text tags update.

**Comment by petzku** [comment]
@bucket3432 sorry, this fell through the cracks for a while. Is it ready to review now?

**Comment by bucket3432** [comment]
@petzku Yes, this is ready for review.

**Review by petzku — APPROVED** [review]
Looks good!

**Pull request merged**
